import auto from "./images/auto.JPG";
import smartfitnes from "./images/smartfitnes.JPG";
import shakentake from "./images/shakentake.JPG";
import hotshapers from "./images/hotshapers.JPG";
import scholl from "./images/scholl.JPG";
import hiptrainer from "./images/hiptrainer.JPG";
import cetka from "./images/cetka.JPG";
import hd from "./images/hd.JPG";
import rukavice from "./images/rukavice.JPG";
import magic from "./images/magic.JPG";
import mitiseri from "./images/mitiseri.JPG";
import schollgel from "./images/schollgel.JPG";
import masazerzalice from "./images/masazerzalice.JPG";
import figaro from "./images/figaro.JPG";
import petzoom from "./images/petzoom.JPG";
import rucnimasazer from "./images/rucnimasazer.JPG";
import valjak from "./images/valjak.JPG";
import podrska from "./images/podrska.JPG";
import sega from "./images/sega.JPG";
import sweettrimer from "./images/sweettrimer.JPG";
import finishingtouch from "./images/finishingtouch.JPG";
import gluteus from "./images/gluteus.JPG";
import beljenje from "./images/beljenje.JPG";
import sweetsweat from "./images/sweetsweat.JPG";
import forever from "./images/forever.JPG";
import wonder from "./images/wonder.JPG";
import korset from "./images/korset.JPG";

export const data = [
	{
		id: 1,
		title: "True Touch",
		category: "ljubimci",
		image: auto,
		price: 0,
		stars: 5,
		taxes: 120,
		stocks: 10,
		action: true,
	},
	{
		id: 2,
		title: "Smart Fitnes",
		category: "elektrika",
		image: smartfitnes,
		price: 1690,
		stars: 4.5,
		taxes: 120,
		stocks: 10,
		action: true,
	},
	{
		id: 3,
		title: "Shake N Take",
		category: "elektrika",
		image: shakentake,
		price: 0,
		stars: 4.8,
		taxes: 120,
		stocks: 10,
		action: true,
	},
	{
		id: 4,
		title: "Helanke za mrsavljenje",
		category: "lepota",
		image: hotshapers,
		price: 990,
		stars: 3.0,
		taxes: 120,
		stocks: 10,
		action: true,
	},
	{
		id: 5,
		title: "Scholl",
		category: "lepota",
		image: scholl,
		price: 790,
		stars: 4.8,
		taxes: 120,
		stocks: 10,
		action: true,
	},
	{
		id: 6,
		title: "Hip Trainer",
		category: "lepota",
		image: hiptrainer,
		price: 990,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
		action: true,
	},
	{
		id: 7,
		title: "Cekta za kosu",
		category: "lepota",
		image: cetka,
		price: 999,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
		action: true,
	},
	{
		id: 8,
		title: "HD Vision",
		category: "elektrika",
		image: hd,
		price: 990,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
		action: true,
	},
	{
		id: 9,
		title: "Rukavice za bastu",
		category: "pomoc",
		image: rukavice,
		price: 590,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
		action: true,
	},
	{
		id: 10,
		title: "Magic Mesh",
		category: "pomoc",
		image: magic,
		price: 990,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
	},
	{
		id: 11,
		title: "Protiv Mitisera",
		category: "elektrika",
		image: mitiseri,
		price: 1690,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
	},
	{
		id: 12,
		title: "Ulozak Scholl",
		category: "pomoc",
		image: schollgel,
		price: 500,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
	},
	{
		id: 13,
		title: "Masazer za lice",
		category: "elektrika",
		image: masazerzalice,
		price: 790,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
	},
	{
		id: 14,
		title: "Spiralni Figaro",
		category: "elektrika",
		image: figaro,
		price: 990,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
	},
	{
		id: 15,
		title: "Pet Zoom",
		category: "ljubimci",
		image: petzoom,
		price: 990,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
	},
	{
		id: 16,
		title: "Rucni masazer",
		category: "elektrika",
		image: rucnimasazer,
		price: 1490,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
	},
	{
		id: 17,
		title: "Valjak",
		category: "pomoc",
		image: valjak,
		price: 1490,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
	},
	{
		id: 18,
		title: "Podrska za ledja",
		category: "lepota",
		image: podrska,
		price: 1190,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
	},
	{
		id: 19,
		title: "Sega",
		category: "elektrika",
		image: sega,
		price: 2190,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
	},
	{
		id: 20,
		title: "Sweet Trimer",
		category: "elektrika",
		image: sweettrimer,
		price: 990,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
	},
	{
		id: 21,
		title: "Finishing Touch",
		category: "elektrika",
		image: finishingtouch,
		price: 1490,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
	},
	{
		id: 22,
		title: "Gluteus Elektro Stimulator",
		category: "elektrika",
		image: gluteus,
		price: 1190,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
	},
	{
		id: 23,
		title: "Auto drzac za mobilni",
		category: "pomoc",
		image: auto,
		price: 990,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
	},
	{
		id: 24,
		title: "Pasta za zube",
		category: "lepota",
		image: beljenje,
		price: 650,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
	},
	{
		id: 25,
		title: "Sweet Sweat",
		category: "lepota",
		image: sweetsweat,
		price: 650,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
	},
	{
		id: 26,
		title: "Forever",
		category: "lepota",
		image: forever,
		price: 650,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
	},
	{
		id: 27,
		title: "Wonder Patch",
		category: "lepota",
		image: wonder,
		price: 700,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
	},
	{
		id: 28,
		title: "Korseti",
		category: "lepota",
		image: korset,
		price: 700,
		stars: 3.8,
		taxes: 120,
		stocks: 10,
	},
];
